# Generated by Django 5.2.5 on 2025-08-11 02:30

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["update_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="lnglat",
            field=models.CharField(
                blank=True,
                help_text="경도, 위도 포맷",
                max_length=100,
                null=True,
                validators=[blog.models.lnglat_validator],
                verbose_name="경,위도",
            ),
        ),
    ]
