# Generated by Django 5.2.5 on 2025-08-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_post_lnglat"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
