# Generated by Django 5.2.5 on 2025-08-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default="um", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
