# Generated by Django 5.2.5 on 2025-08-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_tag_name_alter_tag_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
