-- SEQUENCE : 순차적인 번호를 자동으로 생성하는 객체. 대부분 인위적인 PK 사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1붙 시작(기본값)
    INCREMENT BY 1 -- 1씩 증가(기본값)
    MAXVALUE 9999  -- 최댓값
    MINVALUE 1     -- 최솟값
    NOCYCLE -- CYCLE : 순차번호 9999->1
    NOCACHE; 

SELECT FRIEND_SEQ.NEXTVAL FROM DUAL;  -- 다음 순차번호 값
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;  -- 현재 시퀀스 값

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    TEL VARCHAR(20) UNIQUE,
    ADDRESS VARCHAR(250),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCACHE NOCYCLE;
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999','서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '유길동', NULL,'서울');
DELETE FROM FRIEND WHERE TEL IS NULL;


-- 연습문제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(20) NOT NULL
);

CREATE TABLE MEMBER(
    MNO NUMBER(4) PRIMARY KEY,
    MNAME VARCHAR2(20) NOT NULL,
    MPW VARCHAR(20) NOT NULL,
    MMAIL VARCHAR2(50) UNIQUE,
    MPOINT NUMBER(5) CHECK (MPOINT>=0),
    MRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
    MAXVALUE 9999
    NOCACHE NOCYCLE;
INSERT INTO MEMBER_LEVEL VALUES(-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES(0, '일반');
INSERT INTO MEMBER_LEVEL VALUES(1, '실버');
INSERT INTO MEMBER_LEVEL VALUES(2, '골드');
SELECT * FROM MEMBER_LEVEL;

INSERT INTO MEMBER VALUES(MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, '24/09/26',0);
INSERT INTO MEMBER VALUES(MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, '22/04/21',1);
SELECT MNO, MNAME, TO_CHAR(MRDATE,'yyyy-MM-DD') mRADTE,MMAIL, MPOINT POINT, LEVELNAME || '고객' levelname
    FROM MEMBER M, MEMBER_LEVEL ML
    WHERE M.LEVELNO = ML.LEVELNO;